/** Metadata only: importing the catalog never imports exercise implementations. */
import type { TrainingCatalogItem } from './contracts';

export const TRAINING_CATALOG: readonly TrainingCatalogItem[] = [
  {
    id: 'schulte',
    title: '数字顺序搜索',
    enTitle: 'Schulte Grid',
    description: '在随机网格中按指定顺序寻找数字；提供正序、逆序与双端交替三种规则。',
    construct: '顺序视觉搜索 · 快速选择',
    route: '/games/brain-training/schulte',
    symbol: '1→N',
    accent: '#0f766e',
    darkAccent: '#5eead4',
    duration: '1–3 min',
  },
  {
    id: 'flanker',
    title: '箭头冲突',
    enTitle: 'Flanker Task',
    description: '只判断中央箭头方向，同时忽略两侧一致或冲突的干扰箭头。',
    construct: '目标选择 · 干扰控制',
    route: '/games/brain-training/flanker',
    symbol: '→',
    accent: '#2563eb',
    darkAccent: '#93c5fd',
    duration: '2–4 min',
  },
  {
    id: 'n-back',
    title: '位置更新',
    enTitle: 'Spatial N-back',
    description: '判断当前亮起的位置是否与前第 n 个刺激相同。',
    construct: '持续更新 · 时间顺序匹配',
    route: '/games/brain-training/n-back',
    symbol: 'n−',
    accent: '#7c3aed',
    darkAccent: '#c4b5fd',
    duration: '3–5 min',
  },
  {
    id: 'task-switching',
    title: '规则切换',
    enTitle: 'Task Switching',
    description: '根据线索在奇偶与大小两套判断规则之间切换。',
    construct: '规则保持 · 任务集切换',
    route: '/games/brain-training/task-switching',
    symbol: '⇄',
    accent: '#b45309',
    darkAccent: '#fdba74',
    duration: '3–5 min',
  },
  {
    id: 'multiple-object-tracking',
    title: '多目标追踪',
    enTitle: 'Multiple Object Tracking',
    description: '标记若干目标，在相同物体持续移动后重新识别它们。',
    construct: '动态视觉注意 · 多目标保持',
    route: '/games/brain-training/multiple-object-tracking',
    symbol: '•••',
    accent: '#be185d',
    darkAccent: '#f9a8d4',
    duration: '2–4 min',
  },
  {
    id: 'mental-rotation',
    title: '心理旋转',
    enTitle: 'Mental Rotation',
    description: '判断离散几何图形是旋转后的同一形状，还是镜像形状。',
    construct: '空间表征 · 内部变换',
    route: '/games/brain-training/mental-rotation',
    symbol: '↻',
    accent: '#15803d',
    darkAccent: '#86efac',
    duration: '3–5 min',
  },
  {
    id: 'change-localization',
    title: '变化定位',
    enTitle: 'Change Localization',
    description: '记住颜色与形状的位置，并指出保持间隔后发生变化的项目。',
    construct: '短时保持 · 变化比较',
    route: '/games/brain-training/change-localization',
    symbol: 'Δ',
    accent: '#0e7490',
    darkAccent: '#67e8f9',
    duration: '3–5 min',
  },
] as const;
